name: GitHub for IT Pro CI/CD Pipeline
env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:
      
  # publish IaC as build artifact
  uploadIaC:
    runs-on: windows-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # upload IaC folder
    - name: upload IaC
      uses: actions/upload-artifact@master
      with:
        name: IaC
        path: ${{ env.OUTPUT_PATH }}

  # provision infrastructure in Azure
  provisionInfra:
    needs: uploadIaC
    runs-on: windows-latest
    steps:
    # download IaC artifact
    - name: download IaC
      uses: actions/download-artifact@master
      with:
        name: IaC
        path: ${{ env.OUTPUT_PATH }}

    - name: look for ps1 file
      run: |
        ls '${{ github.workspace }}\IaC\AzCLI'

    - name: provision virtual machine in azure
      env:
        SERVICE_PRINCIPAL: http://SarahDeployPrincipal
        SERVICE_PRINCIPAL_TENANT: 72f988bf-86f1-41af-91ab-2d7cd011db47
        AZURE_SUBSCRIPTION_NAME: "Microsoft Azure Internal Consumption"
        RESOURCE_GROUP: rg-githubitpro
        RESOURCE_GROUP_REGION: southcentralus
        SERVER_NAME: gihtubactions
        ADMIN_LOGIN: sarah
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'" 
        -servicePrincipal %SERVICE_PRINCIPAL% 
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId %SERVICE_PRINCIPAL_TENANT% 
        -azureSubscriptionName %AZURE_SUBSCRIPTION_NAME% 
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 
        -serverName %SERVER_NAME% 
        -dbLocation %DB_LOCATION% 
        -adminLogin %ADMIN_LOGIN% 
        -adminPassword ${{ secrets.ADMIN_PASSWORD }} 

